strava:
  client_id: 111
  client_secret: xxxx
mongo_db:
  cluster: xxx
  user: xxxx
  pwd: xxxx
athletes:
  Jesus:
    strava_code: xxxx
    tokens:
      access_token: xxxx
      refresh_token: xxxx
